// Interview.jsx
// MyStory.Family — Buyer dashboard and Getting Started flow
// Lives at /interview on mystory.family
//
// This is a self-contained React component. Drop it into your existing
// Vite + React project, add the route, and configure Vercel to serve it.

import React, { useState, useEffect, useRef } from 'react';
import { createClient } from '@supabase/supabase-js';

// ============================================================
// Supabase client — uses the same env vars as your existing app
// ============================================================
const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY
);

// ============================================================
// Brand palette (inline to match your existing app's approach)
// ============================================================
const colors = {
  navy: '#2C3E50',
  gold: '#D4A574',
  olive: '#7A8B6F',
  tan: '#A67B5B',
  cream: '#F8F5F0',
  creamLight: '#FBF8F3',
  creamWarm: '#FFFBF5',
  gray: '#C4B5A0',
  border: '#E8E0D0',
  borderSubtle: '#F0EBE2',
  text: '#1A2330',
  textSecondary: '#5C6470',
  textTertiary: '#8B8478',
};

const fonts = {
  serif: '"Playfair Display", Georgia, "Times New Roman", serif',
  sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
};

// ============================================================
// Chunk 1 — scripted welcome from Grace
// (Chunks 2-6 are generated by the API)
// ============================================================
const CHUNK_1_WELCOME = (buyerName) => [
  { type: 'heading', text: `Hello, ${buyerName || 'there'}. I'm Grace.` },
  { type: 'paragraph', text: "I'm so glad you're here. Before we go any further, I want to tell you what we're doing together — and what you can expect from me." },
  { type: 'paragraph', text: "Over the next fifteen minutes or so, I'd like to get to know you, and to learn about the person whose stories we're going to capture. I'll ask about who they are, what matters most to you about this project, and what we should be careful with along the way. Everything you share helps us shape the right conversations later — the questions we'll bring to them, the pace we'll set, the pieces of their life we'll make sure get covered." },
  { type: 'paragraph', text: "Two things I want you to know up front." },
  { type: 'paragraph', text: "First: there are no wrong answers, and no right ones. You can pause anytime and come back — I'll save where we are. If a question doesn't fit, just tell me, and we'll move on." },
  { type: 'paragraph', text: "Second — and this matters: I'm not here to tell their story for them. Their story is theirs to tell, in their own words, when you sit down with them. What we're doing together right now is making sure I can help you draw those stories out as carefully as they deserve." },
  { type: 'paragraph', text: "When we're done, we'll have a real plan — five conversations that, together, will become a book your family will hold for generations. I take that seriously. I think you do too." },
  { type: 'paragraph', text: "Ready when you are." },
];

const CHUNK_NAMES = {
  1: 'A welcome from Grace',
  2: 'About you',
  3: 'About your subject',
  4: 'What to be careful about',
  5: 'What you hope they\'ll talk about',
  6: 'Your project plan',
};

// ============================================================
// Main Interview app — handles routing between dashboard and pages
// ============================================================
export default function Interview() {
  const [user, setUser] = useState(null);
  const [authLoading, setAuthLoading] = useState(true);
  const [project, setProject] = useState(null);
  const [view, setView] = useState('dashboard'); // 'dashboard' or 'getting_started'

  // Load the authenticated user on mount
  useEffect(() => {
    const loadUser = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      setUser(user);
      setAuthLoading(false);
    };
    loadUser();

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setUser(session?.user ?? null);
    });

    return () => subscription.unsubscribe();
  }, []);

  // Load or create the user's project
  useEffect(() => {
    if (!user) return;

    const loadProject = async () => {
      // Try to find an existing project for this user
      const { data: projects, error } = await supabase
        .from('interview_projects')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })
        .limit(1);

      if (error) {
        console.error('Error loading project:', error);
        return;
      }

      if (projects && projects.length > 0) {
        setProject(projects[0]);
      } else {
        // Create a new project — pull buyer name from user metadata if available
        const buyerName =
          user.user_metadata?.full_name ||
          user.user_metadata?.name ||
          user.email?.split('@')[0] ||
          '';

        const { data: newProject, error: createError } = await supabase
          .from('interview_projects')
          .insert({ user_id: user.id, buyer_name: buyerName })
          .select()
          .single();

        if (createError) {
          console.error('Error creating project:', createError);
          return;
        }
        setProject(newProject);
      }
    };

    loadProject();
  }, [user]);

  if (authLoading) {
    return <LoadingScreen />;
  }

  if (!user) {
    return <SignInScreen />;
  }

  if (!project) {
    return <LoadingScreen message="Setting up your project..." />;
  }

  if (view === 'getting_started') {
    return (
      <GettingStarted
        project={project}
        onProjectUpdate={setProject}
        onReturnToDashboard={() => setView('dashboard')}
      />
    );
  }

  return (
    <Dashboard
      user={user}
      project={project}
      onBeginGettingStarted={() => setView('getting_started')}
    />
  );
}

// ============================================================
// Loading screen
// ============================================================
function LoadingScreen({ message = 'Loading...' }) {
  return (
    <div style={{
      minHeight: '100vh',
      background: colors.cream,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontFamily: fonts.sans,
      color: colors.textSecondary,
    }}>
      {message}
    </div>
  );
}

// ============================================================
// Sign-in screen — placeholder, swap in your real auth UI
// ============================================================
function SignInScreen() {
  const [email, setEmail] = useState('');
  const [sent, setSent] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    const { error } = await supabase.auth.signInWithOtp({
      email,
      options: { emailRedirectTo: window.location.href },
    });
    if (error) {
      setError(error.message);
    } else {
      setSent(true);
    }
  };

  return (
    <div style={{
      minHeight: '100vh',
      background: colors.cream,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontFamily: fonts.sans,
      padding: '2rem',
    }}>
      <div style={{
        background: 'white',
        borderRadius: '16px',
        padding: '40px',
        maxWidth: '440px',
        width: '100%',
        border: `0.5px solid ${colors.border}`,
      }}>
        <h1 style={{
          fontFamily: fonts.serif,
          fontSize: '24px',
          fontWeight: 500,
          color: colors.navy,
          margin: '0 0 8px',
        }}>
          MyStory<span style={{ color: colors.gold }}>.</span>Family
        </h1>
        <p style={{ fontSize: '14px', color: colors.textSecondary, margin: '0 0 24px' }}>
          Sign in to continue your project.
        </p>

        {sent ? (
          <p style={{ fontSize: '14px', color: colors.olive, lineHeight: 1.6 }}>
            Check your email — we've sent you a link to sign in.
          </p>
        ) : (
          <form onSubmit={handleSubmit}>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="your@email.com"
              required
              style={{
                width: '100%',
                padding: '12px 14px',
                fontSize: '15px',
                border: `0.5px solid ${colors.border}`,
                borderRadius: '8px',
                marginBottom: '12px',
                fontFamily: 'inherit',
                boxSizing: 'border-box',
              }}
            />
            <button
              type="submit"
              style={{
                width: '100%',
                padding: '12px',
                fontSize: '15px',
                background: colors.navy,
                color: 'white',
                border: 'none',
                borderRadius: '999px',
                cursor: 'pointer',
                fontWeight: 500,
                fontFamily: 'inherit',
              }}
            >
              Send sign-in link
            </button>
            {error && <p style={{ color: '#B8543D', fontSize: '13px', marginTop: '12px' }}>{error}</p>}
          </form>
        )}
      </div>
    </div>
  );
}

// ============================================================
// Dashboard — the main hub
// ============================================================
function Dashboard({ user, project, onBeginGettingStarted }) {
  const subject = project.subject_name || 'your loved one';
  const buyerInitials = (project.buyer_name || user.email || '?')
    .split(' ').map(s => s[0]).join('').slice(0, 2).toUpperCase();

  // Determine the greeting and active step
  const getGreeting = () => {
    if (!project.getting_started_complete) {
      return {
        eyebrow: project.subject_name ? `${project.subject_name}'s life story` : 'A new project',
        heading: `Welcome${project.buyer_name ? `, ${project.buyer_name}` : ''}.`,
        body: 'Let\'s begin by getting to know your family. Start with Getting Started below.',
      };
    }
    // Future states (after Getting Started is done) — placeholders for now
    return {
      eyebrow: `${subject}'s life story`,
      heading: `Welcome back${project.buyer_name ? `, ${project.buyer_name}` : ''}.`,
      body: 'Your next step is ready when you are.',
    };
  };

  const greeting = getGreeting();

  // Determine which step is active
  const activeStep = !project.getting_started_complete
    ? 'getting_started'
    : !project.interviewer_guide_complete
    ? 'interviewer_guide'
    : !project.capturing_conversations_complete
    ? 'capturing_conversations'
    : 'conversation_1';

  // Calculate progress
  const totalSteps = 8;
  const completedSteps =
    (project.getting_started_complete ? 1 : 0) +
    (project.interviewer_guide_complete ? 1 : 0) +
    (project.capturing_conversations_complete ? 1 : 0);

  return (
    <div style={{
      minHeight: '100vh',
      background: colors.cream,
      fontFamily: fonts.sans,
      color: colors.text,
    }}>
      <div style={{
        maxWidth: '900px',
        margin: '0 auto',
        padding: '20px 16px',
      }}>
        <div style={{
          background: 'white',
          borderRadius: '16px',
          overflow: 'hidden',
          border: `0.5px solid ${colors.border}`,
        }}>
          {/* Header */}
          <Header buyerInitials={buyerInitials} buyerName={project.buyer_name} />

          {/* Hero */}
          <Hero greeting={greeting} />

          {/* Progress bar */}
          <ProgressBar completed={completedSteps} total={totalSteps} />

          {/* Active step */}
          <Section
            barColor={colors.gold}
            title={activeStep === 'getting_started' ? 'Start here' : 'Continue where you left off'}
          >
            {activeStep === 'getting_started' && (
              <ActiveCard
                eyebrow="Begin · Step 1 of 3"
                title="Getting started"
                description="Tell me about your family and what you hope to capture. About 15 minutes."
                buttonText="Begin →"
                onClick={onBeginGettingStarted}
                icon={<IconGetting />}
              />
            )}
            {/* Add other active states here as more pages get built */}
          </Section>

          {/* Preparation steps */}
          <Section
            barColor={colors.gray}
            title="Your preparation"
            subtitle={!project.getting_started_complete ? '— unlocks after Getting started' : null}
          >
            <CardGrid>
              <LockedCard
                title="Your interviewer guide"
                subtitle="Step 2 of 3"
                icon={<IconGuide />}
                locked={!project.getting_started_complete}
              />
              <LockedCard
                title="Capturing your conversations"
                subtitle="Step 3 of 3"
                icon={<IconRecord />}
                locked={!project.interviewer_guide_complete}
              />
            </CardGrid>
          </Section>

          {/* Conversations */}
          <Section
            barColor={colors.gray}
            title="Your conversations"
            subtitle={!project.capturing_conversations_complete ? '— unlocks after preparation' : null}
          >
            <CardGrid>
              <LockedCard title="Early life" subtitle="Conversation 1" icon={<IconHouse />} locked />
              <LockedCard title="Formative years" subtitle="Conversation 2" icon={<IconPerson />} locked />
              <LockedCard title="Faith" subtitle="Conversation 3" icon={<IconCross />} locked />
              <LockedCard title="Marriage & family" subtitle="Conversation 4" icon={<IconFamily />} locked />
              <LockedCard title="Reflections" subtitle="Conversation 5" icon={<IconReflect />} locked />
              <LockedCard title="Add a topic" subtitle="Optional · After Conversation 5" icon={<IconPlus />} locked dashed />
            </CardGrid>
          </Section>

          {/* Book footer */}
          <BookFooter subject={subject} hasContent={false} />
        </div>
      </div>
    </div>
  );
}

// ============================================================
// Header
// ============================================================
function Header({ buyerInitials, buyerName }) {
  return (
    <div style={{
      background: colors.navy,
      padding: '14px 24px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
    }}>
      <div style={{
        fontFamily: fonts.serif,
        fontSize: '17px',
        fontWeight: 500,
        color: 'white',
      }}>
        MyStory<span style={{ color: colors.gold }}>.</span>Family
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
        {buyerName && (
          <div style={{ fontSize: '13px', color: 'rgba(255,255,255,0.75)' }}>
            {buyerName}
          </div>
        )}
        <div style={{
          width: '30px', height: '30px', borderRadius: '50%',
          background: colors.gold,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: '12px', fontWeight: 500, color: colors.navy,
        }}>
          {buyerInitials}
        </div>
      </div>
    </div>
  );
}

// ============================================================
// Hero zone — placeholder until illustration arrives
// ============================================================
function Hero({ greeting }) {
  return (
    <div style={{
      position: 'relative',
      height: '240px',
      overflow: 'hidden',
      background: `linear-gradient(135deg, #E8D5B7 0%, #C9A574 50%, #A67B5B 100%)`,
    }}>
      <div style={{
        position: 'absolute', inset: 0,
        background: 'linear-gradient(180deg, rgba(44,62,80,0.05) 0%, rgba(44,62,80,0.55) 100%)',
      }} />
      <div style={{
        position: 'absolute', inset: 0,
        display: 'flex', flexDirection: 'column',
        justifyContent: 'flex-end',
        padding: '0 32px 24px',
      }}>
        <p style={{
          fontSize: '12px', color: 'rgba(255,255,255,0.85)',
          margin: '0 0 6px', letterSpacing: '1.5px', textTransform: 'uppercase',
        }}>
          {greeting.eyebrow}
        </p>
        <h1 style={{
          fontFamily: fonts.serif, fontSize: '30px', fontWeight: 500,
          color: 'white', margin: '0 0 6px',
          lineHeight: 1.15, letterSpacing: '-0.5px',
        }}>
          {greeting.heading}
        </h1>
        <p style={{
          fontSize: '14px', color: 'rgba(255,255,255,0.92)',
          margin: 0, lineHeight: 1.5, maxWidth: '460px',
        }}>
          {greeting.body}
        </p>
      </div>
    </div>
  );
}

// ============================================================
// Progress bar
// ============================================================
function ProgressBar({ completed, total }) {
  const pct = (completed / total) * 100;
  return (
    <div style={{
      padding: '24px 24px 18px',
      borderBottom: `0.5px solid ${colors.border}`,
    }}>
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        marginBottom: '8px',
      }}>
        <span style={{
          fontSize: '12px', color: colors.textSecondary,
          letterSpacing: '0.5px', textTransform: 'uppercase',
        }}>
          Your progress
        </span>
        <span style={{ fontSize: '13px', color: colors.text, fontWeight: 500 }}>
          {completed} of {total} steps
        </span>
      </div>
      <div style={{
        height: '6px', background: colors.borderSubtle,
        borderRadius: '3px', overflow: 'hidden',
      }}>
        <div style={{
          width: `${pct}%`, height: '100%', background: colors.gold,
          transition: 'width 0.3s ease',
        }} />
      </div>
    </div>
  );
}

// ============================================================
// Section — wraps a labeled group of cards
// ============================================================
function Section({ barColor, title, subtitle, children }) {
  return (
    <div style={{ padding: '24px 24px 8px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
        <div style={{ width: '4px', height: '16px', background: barColor, borderRadius: '2px' }} />
        <h2 style={{
          fontFamily: fonts.serif, fontSize: '18px', fontWeight: 500, margin: 0,
        }}>
          {title}
        </h2>
        {subtitle && (
          <span style={{ fontSize: '12px', color: colors.textTertiary, marginLeft: '4px' }}>
            {subtitle}
          </span>
        )}
      </div>
      {children}
    </div>
  );
}

// ============================================================
// Active card — the highlighted current step
// ============================================================
function ActiveCard({ eyebrow, title, description, buttonText, onClick, icon }) {
  return (
    <div style={{
      background: colors.creamWarm,
      border: `1.5px solid ${colors.gold}`,
      borderRadius: '12px',
      padding: '18px',
      display: 'flex',
      alignItems: 'center',
      gap: '18px',
    }}>
      <div style={{ flexShrink: 0 }}>{icon}</div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{
          fontSize: '11px', color: colors.tan, fontWeight: 500,
          letterSpacing: '0.8px', textTransform: 'uppercase', marginBottom: '4px',
        }}>
          {eyebrow}
        </div>
        <div style={{
          fontFamily: fonts.serif, fontSize: '18px', fontWeight: 500, marginBottom: '4px',
        }}>
          {title}
        </div>
        <div style={{
          fontSize: '13px', color: colors.textSecondary, lineHeight: 1.5, marginBottom: '12px',
        }}>
          {description}
        </div>
        <button onClick={onClick} style={{
          fontSize: '13px', padding: '9px 22px',
          background: colors.navy, color: 'white',
          border: 'none', borderRadius: '999px', cursor: 'pointer',
          fontWeight: 500, fontFamily: 'inherit',
        }}>
          {buttonText}
        </button>
      </div>
    </div>
  );
}

// ============================================================
// Locked card
// ============================================================
function LockedCard({ title, subtitle, icon, locked, dashed }) {
  return (
    <div style={{
      background: colors.creamLight,
      border: `0.5px ${dashed ? 'dashed' : 'solid'} ${colors.border}`,
      borderRadius: '12px',
      padding: '14px',
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      opacity: locked ? 0.6 : 1,
    }}>
      <div style={{ flexShrink: 0 }}>{icon}</div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: '13px', fontWeight: 500, marginBottom: '2px' }}>{title}</div>
        <div style={{ fontSize: '11px', color: colors.textTertiary }}>
          {subtitle}{locked ? ' · Locked' : ''}
        </div>
      </div>
    </div>
  );
}

// ============================================================
// Card grid
// ============================================================
function CardGrid({ children }) {
  return (
    <div style={{
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
      gap: '12px',
    }}>
      {children}
    </div>
  );
}

// ============================================================
// Book footer
// ============================================================
function BookFooter({ subject, hasContent }) {
  return (
    <div style={{
      borderTop: `0.5px solid ${colors.border}`,
      padding: '20px 24px',
      background: colors.creamLight,
      display: 'flex',
      alignItems: 'center',
      gap: '16px',
    }}>
      <IconBook locked={!hasContent} />
      <div style={{ flex: 1 }}>
        <div style={{
          fontFamily: fonts.serif, fontSize: '16px', fontWeight: 500, marginBottom: '3px',
        }}>
          {subject}'s book
        </div>
        <div style={{ fontSize: '12px', color: colors.textSecondary, lineHeight: 1.5 }}>
          {hasContent
            ? 'View what we\'ve captured so far'
            : 'Begins taking shape after your first conversation'}
        </div>
      </div>
    </div>
  );
}

// ============================================================
// Getting Started page
// ============================================================
function GettingStarted({ project, onProjectUpdate, onReturnToDashboard }) {
  const [currentChunk, setCurrentChunk] = useState(1);
  const [chunkStatuses, setChunkStatuses] = useState({});
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [hasStarted, setHasStarted] = useState(false);
  const [error, setError] = useState('');
  const messagesEndRef = useRef(null);

  // Load existing chunks and messages on mount
  useEffect(() => {
    const loadProgress = async () => {
      const { data: chunks } = await supabase
        .from('interview_orientation_chunks')
        .select('*')
        .eq('project_id', project.id)
        .order('chunk_number');

      const { data: msgs } = await supabase
        .from('interview_messages')
        .select('*')
        .eq('project_id', project.id)
        .order('created_at');

      if (chunks) {
        const statusMap = {};
        chunks.forEach(c => { statusMap[c.chunk_number] = c.status; });
        setChunkStatuses(statusMap);

        // Determine current chunk: first non-complete one, default to 1
        const firstIncomplete = chunks.find(c => c.status !== 'complete');
        if (firstIncomplete) {
          setCurrentChunk(firstIncomplete.chunk_number);
          setHasStarted(firstIncomplete.chunk_number > 1);
        } else if (chunks.length > 0) {
          // All chunks complete
          setCurrentChunk(6);
          setHasStarted(true);
        }
      }

      if (msgs) {
        setMessages(msgs);
      }
    };

    loadProgress();
  }, [project.id]);

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  // Begin chunk 2 — sends a "let's begin" signal to Grace
  const handleBegin = async () => {
    setHasStarted(true);
    setCurrentChunk(2);

    // Mark chunk 1 as complete
    await supabase.from('interview_orientation_chunks').upsert({
      project_id: project.id,
      chunk_number: 1,
      chunk_name: 'welcome',
      status: 'complete',
      completed_at: new Date().toISOString(),
    }, { onConflict: 'project_id,chunk_number' });

    // Mark chunk 2 as in progress
    await supabase.from('interview_orientation_chunks').upsert({
      project_id: project.id,
      chunk_number: 2,
      chunk_name: 'about_you',
      status: 'in_progress',
      started_at: new Date().toISOString(),
    }, { onConflict: 'project_id,chunk_number' });

    setChunkStatuses(prev => ({ ...prev, 1: 'complete', 2: 'in_progress' }));

    // Ask Grace to start chunk 2
    await sendToGrace(null, 2);
  };

  // Send message to Grace and handle response
  const sendToGrace = async (userMessage, chunkNumber) => {
    setLoading(true);
    setError('');

    try {
      // Save user message if there is one
      if (userMessage) {
        const { data: savedMsg } = await supabase
          .from('interview_messages')
          .insert({
            project_id: project.id,
            chunk_number: chunkNumber,
            role: 'buyer',
            content: userMessage,
          })
          .select()
          .single();

        if (savedMsg) setMessages(prev => [...prev, savedMsg]);
      }

      // Build conversation history for the API
      const history = messages.map(m => ({
        role: m.role === 'grace' ? 'assistant' : 'user',
        content: m.content,
      }));

      if (userMessage) {
        history.push({ role: 'user', content: userMessage });
      } else {
        // First message in chunk — prompt Grace to start it
        history.push({
          role: 'user',
          content: `[System: The buyer has just started chunk ${chunkNumber}. Begin this chunk.]`,
        });
      }

      // Call your /api/claude endpoint
      const response = await fetch('/api/claude', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: history,
          project: project,
          currentChunk: chunkNumber,
          mode: 'getting_started',
        }),
      });

      if (!response.ok) {
        throw new Error(`API returned ${response.status}`);
      }

      const data = await response.json();
      let graceResponse = data.response || data.content || '';

      // Check for chunk complete signal
      const isComplete = graceResponse.includes('[CHUNK_COMPLETE]');
      if (isComplete) {
        graceResponse = graceResponse.replace('[CHUNK_COMPLETE]', '').trim();
      }

      // Save Grace's response
      const { data: savedGrace } = await supabase
        .from('interview_messages')
        .insert({
          project_id: project.id,
          chunk_number: chunkNumber,
          role: 'grace',
          content: graceResponse,
        })
        .select()
        .single();

      if (savedGrace) setMessages(prev => [...prev, savedGrace]);

      // Handle chunk completion
      if (isComplete) {
        await supabase.from('interview_orientation_chunks').upsert({
          project_id: project.id,
          chunk_number: chunkNumber,
          chunk_name: ['', 'welcome', 'about_you', 'about_subject', 'sensitivities', 'hopes', 'summary'][chunkNumber],
          status: 'complete',
          completed_at: new Date().toISOString(),
        }, { onConflict: 'project_id,chunk_number' });

        setChunkStatuses(prev => ({ ...prev, [chunkNumber]: 'complete' }));

        // Advance to next chunk if not the final one
        if (chunkNumber < 6) {
          const nextChunk = chunkNumber + 1;
          setCurrentChunk(nextChunk);

          await supabase.from('interview_orientation_chunks').upsert({
            project_id: project.id,
            chunk_number: nextChunk,
            chunk_name: ['', 'welcome', 'about_you', 'about_subject', 'sensitivities', 'hopes', 'summary'][nextChunk],
            status: 'in_progress',
            started_at: new Date().toISOString(),
          }, { onConflict: 'project_id,chunk_number' });

          setChunkStatuses(prev => ({ ...prev, [nextChunk]: 'in_progress' }));

          // Auto-prompt Grace to start the next chunk after a brief pause
          setTimeout(() => sendToGrace(null, nextChunk), 500);
        } else {
          // All chunks complete
          await supabase
            .from('interview_projects')
            .update({ getting_started_complete: true, current_step: 'interviewer_guide' })
            .eq('id', project.id);

          onProjectUpdate({ ...project, getting_started_complete: true, current_step: 'interviewer_guide' });
        }
      }
    } catch (err) {
      console.error('Error talking to Grace:', err);
      setError('Something went wrong. Please try again, or come back later — your progress is saved.');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e?.preventDefault();
    if (!input.trim() || loading) return;
    const message = input.trim();
    setInput('');
    await sendToGrace(message, currentChunk);
  };

  const handleSkip = async () => {
    if (loading) return;
    await sendToGrace("[The buyer has chosen to skip this question. Acknowledge gently and move on.]", currentChunk);
  };

  const buyerName = project.buyer_name || '';
  const welcomeContent = CHUNK_1_WELCOME(buyerName);

  return (
    <div style={{
      minHeight: '100vh',
      background: colors.cream,
      fontFamily: fonts.sans,
      color: colors.text,
    }}>
      <div style={{ maxWidth: '900px', margin: '0 auto', padding: '20px 16px' }}>
        <div style={{
          background: 'white',
          borderRadius: '16px',
          overflow: 'hidden',
          border: `0.5px solid ${colors.border}`,
        }}>
          {/* Header with save/exit */}
          <div style={{
            background: colors.navy,
            padding: '14px 24px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
              <button onClick={onReturnToDashboard} style={{
                fontSize: '12px', padding: '5px 10px',
                background: 'rgba(255,255,255,0.1)', color: 'white',
                border: '0.5px solid rgba(255,255,255,0.25)',
                borderRadius: '6px', cursor: 'pointer', fontFamily: 'inherit',
              }}>
                {hasStarted ? '← Save & exit' : '← Dashboard'}
              </button>
              <div style={{ fontFamily: fonts.serif, fontSize: '15px', fontWeight: 500, color: 'white' }}>
                MyStory<span style={{ color: colors.gold }}>.</span>Family
              </div>
            </div>
            {hasStarted && (
              <div style={{ fontSize: '11px', color: 'rgba(255,255,255,0.6)' }}>
                Auto-saved
              </div>
            )}
          </div>

          {/* Step header with chunk indicator */}
          <div style={{
            padding: '16px 24px',
            background: colors.creamLight,
            borderBottom: `0.5px solid ${colors.border}`,
          }}>
            <div style={{
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              maxWidth: '640px', margin: '0 auto', flexWrap: 'wrap', gap: '12px',
            }}>
              <div>
                <div style={{
                  fontSize: '11px', color: colors.textTertiary,
                  letterSpacing: '0.8px', textTransform: 'uppercase', marginBottom: '3px',
                }}>
                  Step 1 of 3
                </div>
                <div style={{ fontFamily: fonts.serif, fontSize: '16px', fontWeight: 500 }}>
                  Getting started
                </div>
              </div>
              <ChunkIndicator current={currentChunk} statuses={chunkStatuses} />
            </div>
          </div>

          {/* Body */}
          <div style={{ padding: '36px 24px 32px', maxWidth: '640px', margin: '0 auto' }}>

            {/* Chunk 1: scripted welcome (only shown before user clicks "Let's begin") */}
            {!hasStarted && (
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '24px' }}>
                  <div style={{ width: '4px', height: '16px', background: colors.gold, borderRadius: '2px' }} />
                  <div style={{
                    fontFamily: fonts.serif, fontSize: '14px', fontWeight: 500,
                    color: colors.textSecondary, letterSpacing: '0.3px',
                  }}>
                    A welcome from Grace
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '18px', marginBottom: '28px' }}>
                  <GraceAvatar size="large" />
                  <div style={{ flex: 1 }}>
                    {welcomeContent.map((item, i) => (
                      item.type === 'heading' ? (
                        <div key={i} style={{
                          fontFamily: fonts.serif, fontSize: '22px', fontWeight: 500,
                          lineHeight: 1.45, color: colors.text, marginBottom: '16px',
                        }}>
                          {item.text}
                        </div>
                      ) : (
                        <div key={i} style={{
                          fontSize: '16px', lineHeight: 1.7, color: colors.navy, marginBottom: '14px',
                        }}>
                          {item.text}
                        </div>
                      )
                    ))}
                  </div>
                </div>

                <div style={{
                  marginTop: '36px', paddingTop: '28px',
                  borderTop: `0.5px solid ${colors.border}`,
                  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                }}>
                  <div style={{ fontSize: '13px', color: colors.textTertiary }}>
                    Ready when you are.
                  </div>
                  <button onClick={handleBegin} style={{
                    fontSize: '14px', padding: '11px 28px',
                    background: colors.navy, color: 'white',
                    border: 'none', borderRadius: '999px', cursor: 'pointer',
                    fontWeight: 500, fontFamily: 'inherit',
                  }}>
                    Let's begin →
                  </button>
                </div>
              </div>
            )}

            {/* Conversation: shown once user has started */}
            {hasStarted && (
              <div>
                {/* Completed chunks as collapsed cards */}
                {[1, 2, 3, 4, 5].filter(n => chunkStatuses[n] === 'complete' && n !== currentChunk).map(n => (
                  <CompletedChunkCard key={n} chunkNumber={n} />
                ))}

                {/* Current chunk header */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '18px' }}>
                  <div style={{ width: '4px', height: '16px', background: colors.gold, borderRadius: '2px' }} />
                  <div style={{
                    fontFamily: fonts.serif, fontSize: '14px', fontWeight: 500,
                    color: colors.textSecondary, letterSpacing: '0.3px',
                  }}>
                    {CHUNK_NAMES[currentChunk]}
                  </div>
                </div>

                {/* Messages in current chunk */}
                {messages.filter(m => m.chunk_number === currentChunk).map((msg, i) => (
                  <Message key={msg.id || i} message={msg} />
                ))}

                {loading && <TypingIndicator />}

                <div ref={messagesEndRef} />

                {/* Input form */}
                {!loading && (
                  <div style={{ marginLeft: '54px', marginTop: '20px' }}>
                    <textarea
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      placeholder="Type your answer here..."
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) handleSubmit();
                      }}
                      style={{
                        width: '100%', minHeight: '110px',
                        padding: '14px 16px',
                        border: `0.5px solid ${colors.border}`,
                        borderRadius: '8px',
                        fontFamily: 'inherit', fontSize: '15px',
                        lineHeight: 1.6, color: colors.text,
                        background: 'white', resize: 'vertical',
                        boxSizing: 'border-box',
                      }}
                    />
                    <div style={{
                      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                      marginTop: '14px', flexWrap: 'wrap', gap: '12px',
                    }}>
                      <button onClick={handleSkip} style={{
                        fontSize: '13px', padding: '7px 14px',
                        background: 'transparent', border: `0.5px solid ${colors.border}`,
                        borderRadius: '6px', cursor: 'pointer',
                        color: colors.textSecondary, fontFamily: 'inherit',
                      }}>
                        Skip this one
                      </button>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                        <span style={{ fontSize: '12px', color: colors.textTertiary }}>
                          ⌘+Enter to send
                        </span>
                        <button onClick={handleSubmit} disabled={!input.trim()} style={{
                          fontSize: '14px', padding: '9px 22px',
                          background: input.trim() ? colors.navy : colors.gray,
                          color: 'white', border: 'none',
                          borderRadius: '999px',
                          cursor: input.trim() ? 'pointer' : 'not-allowed',
                          fontWeight: 500, fontFamily: 'inherit',
                        }}>
                          Send
                        </button>
                      </div>
                    </div>
                    {error && (
                      <div style={{
                        marginTop: '12px', padding: '10px 14px',
                        background: '#FBE9E7', color: '#B8543D',
                        borderRadius: '6px', fontSize: '13px',
                      }}>
                        {error}
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}

          </div>
        </div>
      </div>
    </div>
  );
}

// ============================================================
// Sub-components for Getting Started
// ============================================================
function GraceAvatar({ size = 'small' }) {
  const dim = size === 'large' ? 44 : 36;
  const fontSize = size === 'large' ? 16 : 14;
  return (
    <div style={{
      width: `${dim}px`, height: `${dim}px`, borderRadius: '50%',
      background: '#F4E4C1',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      flexShrink: 0,
      fontFamily: fonts.serif, fontSize: `${fontSize}px`,
      fontWeight: 500, color: colors.tan,
    }}>
      G
    </div>
  );
}

function Message({ message }) {
  if (message.role === 'grace') {
    return (
      <div style={{ display: 'flex', gap: '18px', marginBottom: '24px' }}>
        <GraceAvatar />
        <div style={{ flex: 1 }}>
          {message.content.split('\n').filter(p => p.trim()).map((para, i) => (
            <div key={i} style={{
              fontSize: '16px', lineHeight: 1.7,
              color: i === 0 ? colors.text : colors.navy,
              marginBottom: '12px',
              fontFamily: i === 0 && para.endsWith('?') ? fonts.serif : fonts.sans,
              fontWeight: i === 0 && para.endsWith('?') ? 500 : 400,
            }}>
              {para}
            </div>
          ))}
        </div>
      </div>
    );
  }

  // Buyer message
  return (
    <div style={{ marginLeft: '54px', marginBottom: '20px' }}>
      <div style={{
        background: colors.creamLight,
        borderLeft: `2px solid ${colors.gold}`,
        padding: '14px 16px',
        borderRadius: '0 8px 8px 0',
        fontSize: '15px',
        lineHeight: 1.6,
        color: colors.text,
        whiteSpace: 'pre-wrap',
      }}>
        {message.content}
      </div>
    </div>
  );
}

function TypingIndicator() {
  return (
    <div style={{ display: 'flex', gap: '18px', marginBottom: '24px' }}>
      <GraceAvatar />
      <div style={{
        display: 'flex', alignItems: 'center', gap: '4px',
        padding: '14px 0', color: colors.textTertiary,
      }}>
        <div style={{
          width: '6px', height: '6px', borderRadius: '50%',
          background: colors.tan,
          animation: 'pulse 1.4s ease-in-out infinite',
        }} />
        <div style={{
          width: '6px', height: '6px', borderRadius: '50%',
          background: colors.tan,
          animation: 'pulse 1.4s ease-in-out 0.2s infinite',
        }} />
        <div style={{
          width: '6px', height: '6px', borderRadius: '50%',
          background: colors.tan,
          animation: 'pulse 1.4s ease-in-out 0.4s infinite',
        }} />
        <style>{`
          @keyframes pulse {
            0%, 80%, 100% { opacity: 0.3; }
            40% { opacity: 1; }
          }
        `}</style>
      </div>
    </div>
  );
}

function CompletedChunkCard({ chunkNumber }) {
  return (
    <div style={{
      background: colors.creamLight,
      border: `0.5px solid ${colors.border}`,
      borderRadius: '12px',
      padding: '14px 18px',
      marginBottom: '20px',
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
    }}>
      <div style={{
        width: '18px', height: '18px', borderRadius: '50%',
        background: colors.olive,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        flexShrink: 0,
      }}>
        <svg width="10" height="10" viewBox="0 0 10 10">
          <path d="M2.5 5l1.5 1.5L7.5 3" stroke="white" strokeWidth="1.5"
            fill="none" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </div>
      <div style={{ fontFamily: fonts.serif, fontSize: '14px', color: colors.textSecondary }}>
        {CHUNK_NAMES[chunkNumber]}
      </div>
    </div>
  );
}

function ChunkIndicator({ current, statuses }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
      {[1, 2, 3, 4, 5, 6].map((n, i) => {
        const isComplete = statuses[n] === 'complete';
        const isActive = n === current;
        const bg = isComplete ? colors.olive : isActive ? colors.navy : 'white';
        const border = isComplete || isActive ? 'none' : `1px solid ${colors.border}`;
        const color = isComplete || isActive ? 'white' : colors.textTertiary;

        return (
          <React.Fragment key={n}>
            <div style={{
              width: '24px', height: '24px', borderRadius: '50%',
              background: bg, border: border,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: '11px', fontWeight: isActive ? 500 : 400, color: color,
            }}>
              {isComplete ? (
                <svg width="11" height="11" viewBox="0 0 12 12">
                  <path d="M3 6l2 2 4-4" stroke="white" strokeWidth="1.8"
                    fill="none" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              ) : n}
            </div>
            {i < 5 && (
              <div style={{
                width: '14px', height: '1px',
                background: isComplete || (n + 1 === current) ? colors.gold : colors.border,
              }} />
            )}
          </React.Fragment>
        );
      })}
    </div>
  );
}

// ============================================================
// Icons (SVG illustrations)
// ============================================================
function IconGetting() {
  return (
    <svg width="68" height="68" viewBox="0 0 68 68">
      <circle cx="34" cy="34" r="34" fill="#F4E4C1"/>
      <circle cx="26" cy="28" r="7" fill={colors.tan}/>
      <circle cx="42" cy="28" r="7" fill={colors.tan}/>
      <path d="M 18 44 Q 26 50 34 48 Q 42 50 50 44" stroke={colors.olive}
        strokeWidth="2.5" fill="none" strokeLinecap="round"/>
      <path d="M 30 38 Q 34 41 38 38" stroke={colors.tan} strokeWidth="1.5"
        fill="none" strokeLinecap="round" opacity="0.6"/>
    </svg>
  );
}

function IconGuide() {
  return (
    <svg width="48" height="48" viewBox="0 0 48 48">
      <circle cx="24" cy="24" r="24" fill={colors.borderSubtle}/>
      <rect x="14" y="14" width="20" height="20" rx="2" fill={colors.gray}/>
      <line x1="18" y1="20" x2="30" y2="20" stroke={colors.creamLight} strokeWidth="1.5" strokeLinecap="round"/>
      <line x1="18" y1="24" x2="30" y2="24" stroke={colors.creamLight} strokeWidth="1.5" strokeLinecap="round"/>
      <line x1="18" y1="28" x2="26" y2="28" stroke={colors.creamLight} strokeWidth="1.5" strokeLinecap="round"/>
    </svg>
  );
}

function IconRecord() {
  return (
    <svg width="48" height="48" viewBox="0 0 48 48">
      <circle cx="24" cy="24" r="24" fill={colors.borderSubtle}/>
      <rect x="20" y="14" width="8" height="14" rx="3" fill={colors.gray}/>
      <path d="M 16 26 Q 16 32 24 32 Q 32 32 32 26" stroke={colors.gray} strokeWidth="2" fill="none"/>
      <line x1="24" y1="32" x2="24" y2="36" stroke={colors.gray} strokeWidth="2"/>
      <line x1="20" y1="36" x2="28" y2="36" stroke={colors.gray} strokeWidth="2" strokeLinecap="round"/>
    </svg>
  );
}

function IconHouse() {
  return (
    <svg width="48" height="48" viewBox="0 0 48 48">
      <circle cx="24" cy="24" r="24" fill={colors.borderSubtle}/>
      <rect x="14" y="20" width="20" height="14" rx="1" fill={colors.gray}/>
      <polygon points="14,20 24,13 34,20" fill="#A8987F"/>
      <rect x="21" y="26" width="6" height="8" fill={colors.creamLight}/>
    </svg>
  );
}

function IconPerson() {
  return (
    <svg width="48" height="48" viewBox="0 0 48 48">
      <circle cx="24" cy="24" r="24" fill={colors.borderSubtle}/>
      <path d="M 16 32 L 16 22 Q 16 16 24 16 Q 32 16 32 22 L 32 32" stroke={colors.gray} strokeWidth="2" fill="none"/>
      <circle cx="24" cy="22" r="3" fill={colors.gray}/>
      <path d="M 18 36 Q 24 32 30 36" stroke="#A8987F" strokeWidth="2" fill="none" strokeLinecap="round"/>
    </svg>
  );
}

function IconCross() {
  return (
    <svg width="48" height="48" viewBox="0 0 48 48">
      <circle cx="24" cy="24" r="24" fill={colors.borderSubtle}/>
      <path d="M 24 12 L 24 36 M 16 20 L 32 20" stroke={colors.gray} strokeWidth="2.5" strokeLinecap="round"/>
      <path d="M 20 28 Q 24 32 28 28" stroke="#A8987F" strokeWidth="2" fill="none" strokeLinecap="round"/>
    </svg>
  );
}

function IconFamily() {
  return (
    <svg width="48" height="48" viewBox="0 0 48 48">
      <circle cx="24" cy="24" r="24" fill={colors.borderSubtle}/>
      <circle cx="19" cy="22" r="4" fill={colors.gray}/>
      <circle cx="29" cy="22" r="4" fill={colors.gray}/>
      <path d="M 14 34 Q 19 28 24 30 Q 29 28 34 34" stroke="#A8987F" strokeWidth="2" fill="none" strokeLinecap="round"/>
    </svg>
  );
}

function IconReflect() {
  return (
    <svg width="48" height="48" viewBox="0 0 48 48">
      <circle cx="24" cy="24" r="24" fill={colors.borderSubtle}/>
      <circle cx="18" cy="20" r="4" fill={colors.gray}/>
      <circle cx="30" cy="20" r="4" fill={colors.gray}/>
      <circle cx="24" cy="32" r="4" fill={colors.gray}/>
      <line x1="18" y1="20" x2="24" y2="32" stroke="#A8987F" strokeWidth="1.5"/>
      <line x1="30" y1="20" x2="24" y2="32" stroke="#A8987F" strokeWidth="1.5"/>
      <line x1="18" y1="20" x2="30" y2="20" stroke="#A8987F" strokeWidth="1.5"/>
    </svg>
  );
}

function IconPlus() {
  return (
    <div style={{
      width: '48px', height: '48px', borderRadius: '50%',
      background: colors.borderSubtle,
      display: 'flex', alignItems: 'center', justifyContent: 'center',
    }}>
      <svg width="20" height="20" viewBox="0 0 20 20">
        <path d="M10 4v12M4 10h12" stroke="#A8987F" strokeWidth="2" strokeLinecap="round"/>
      </svg>
    </div>
  );
}

function IconBook({ locked }) {
  const fill = locked ? colors.gray : colors.tan;
  const stripe = locked ? '#E0D4BC' : '#D4C4A8';
  return (
    <svg width="56" height="68" viewBox="0 0 56 68" style={{ flexShrink: 0, opacity: locked ? 0.55 : 1 }}>
      <rect x="6" y="4" width="44" height="60" rx="2" fill={fill}/>
      <rect x="10" y="8" width="36" height="52" rx="1" fill="#FFFBF5"/>
      <line x1="14" y1="18" x2="42" y2="18" stroke={stripe} strokeWidth="1"/>
      <line x1="14" y1="24" x2="42" y2="24" stroke={stripe} strokeWidth="1"/>
      <line x1="14" y1="30" x2="38" y2="30" stroke={stripe} strokeWidth="1"/>
    </svg>
  );
}
